#!/usr/bin/env python3
"""Normalize Ahrefs top-pages snapshot into a path-keyed overlay for build_csv.py.
Source: site-explorer-top-pages (cavallo-inc.com, 2026-06-16 snapshot, all countries).
NOTE: this is a CURRENT-snapshot estimate of monthly organic traffic, not a GSC 12-month sum
(GSC was 403 for this property). value is USD cents in source -> stored as USD dollars."""
import json, os

BASE = os.path.dirname(os.path.abspath(__file__))

# Verbatim pages array from the Ahrefs site-explorer-top-pages response.
PAGES = [
 {"url":"https://cavallo-inc.com/","sum_traffic":1882,"value":175946,"top_keyword":"cavallo","top_keyword_best_position":2,"keywords":69},
 {"url":"https://cavallo-inc.com/product-category/hoof-boot/","sum_traffic":1286,"value":67598,"top_keyword":"cavallo boots","top_keyword_best_position":1,"keywords":34},
 {"url":"https://cavallo-inc.com/how-to-measure/","sum_traffic":180,"value":14958,"top_keyword":"cavallo hoof boots size chart","top_keyword_best_position":2,"keywords":18},
 {"url":"https://cavallo-inc.com/is-navicular-disease-always-the-beginning-of-the-end/","sum_traffic":129,"value":13710,"top_keyword":"when to euthanize a horse with navicular","top_keyword_best_position":2,"keywords":10},
 {"url":"https://cavallo-inc.com/product-category/hoof-boot/trek-hoof-boots/","sum_traffic":85,"value":5497,"top_keyword":"cavallo trek boots","top_keyword_best_position":1,"keywords":5},
 {"url":"https://cavallo-inc.com/shop-cavallo/","sum_traffic":84,"value":5255,"top_keyword":"cavallo boots","top_keyword_best_position":2,"keywords":6},
 {"url":"https://cavallo-inc.com/product-category/hoof-boot-accessories/pastern-wraps/","sum_traffic":75,"value":3842,"top_keyword":"pastern wraps for horses","top_keyword_best_position":2,"keywords":5},
 {"url":"https://cavallo-inc.com/product/trek-pro-hoof-boot/","sum_traffic":44,"value":4331,"top_keyword":"cavallo trek boots","top_keyword_best_position":3,"keywords":8},
 {"url":"https://cavallo-inc.com/ever-heard-of-the-phrase-a-horse-has-five-hearts/","sum_traffic":43,"value":1,"top_keyword":"how many hearts does a horse have","top_keyword_best_position":4,"keywords":8},
 {"url":"https://cavallo-inc.com/product-category/hoof-boot/simple-hoof-boots/","sum_traffic":42,"value":2566,"top_keyword":"cavallo boots","top_keyword_best_position":1,"keywords":6},
 {"url":"https://cavallo-inc.com/product-category/saddle-pads/","sum_traffic":35,"value":1280,"top_keyword":"cavallo saddle pad","top_keyword_best_position":1,"keywords":3},
 {"url":"https://cavallo-inc.com/product/big-foot-draft-size-hoof-boots/","sum_traffic":30,"value":1277,"top_keyword":"draft horse boots","top_keyword_best_position":1,"keywords":7},
 {"url":"https://cavallo-inc.com/faq/cavallo-hoof-boots-for-laminitis/","sum_traffic":27,"value":1395,"top_keyword":"horse boots for laminitis","top_keyword_best_position":5,"keywords":5},
 {"url":"https://cavallo-inc.com/product-category/hoof-boot/mini-hoof-boots/","sum_traffic":26,"value":1261,"top_keyword":"mini horse boots","top_keyword_best_position":2,"keywords":4},
 {"url":"https://www.cavallo-inc.com/wp-content/uploads/2014/05/MeasureChart.pdf","sum_traffic":25,"value":2548,"top_keyword":"cavallo hoof boots size chart","top_keyword_best_position":4,"keywords":5},
 {"url":"https://cavallo-inc.com/working-with-your-horses-unique-personality/","sum_traffic":24,"value":43,"top_keyword":"horse personality","top_keyword_best_position":2,"keywords":6},
 {"url":"https://cavallo-inc.com/product-category/hoof-boot/sport-hoof-boots/","sum_traffic":16,"value":787,"top_keyword":"cavallo sport boots","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/nerves-bloodflow-keeping-the-hoof-alive/","sum_traffic":14,"value":345,"top_keyword":"do horse hooves have nerves","top_keyword_best_position":6,"keywords":9},
 {"url":"https://cavallo-inc.com/product-category/hoof-boot-accessories/hoof-boot-pads/","sum_traffic":13,"value":25,"top_keyword":"boot pad","top_keyword_best_position":4,"keywords":4},
 {"url":"https://cavallo-inc.com/product/leb-long-ear-hoof-boot/","sum_traffic":13,"value":58,"top_keyword":"donkey boots","top_keyword_best_position":2,"keywords":2},
 {"url":"https://cavallo-inc.com/say-hello-to-healthy-heel-bulbs/","sum_traffic":12,"value":None,"top_keyword":"horse heel bulb","top_keyword_best_position":6,"keywords":6},
 {"url":"https://cavallo-inc.com/your-cavallo-laminitis-healing-plan/","sum_traffic":11,"value":135,"top_keyword":"laminitis hoof","top_keyword_best_position":8,"keywords":4},
 {"url":"https://cavallo-inc.com/product-category/hoof-boot-accessories/","sum_traffic":9,"value":448,"top_keyword":"cavallo hoof boots","top_keyword_best_position":11,"keywords":6},
 {"url":"https://cavallo-inc.com/are-you-feeding-your-horse-like-a-cow/","sum_traffic":9,"value":None,"top_keyword":"horse that looks like a cow","top_keyword_best_position":7,"keywords":4},
 {"url":"https://cavallo-inc.com/product/comfort-pad/","sum_traffic":7,"value":252,"top_keyword":"comfort pads","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/cavallos-the-easiest-hoof-boots/","sum_traffic":6,"value":13,"top_keyword":"cavallos","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/fun-halloween-horsey-facts/","sum_traffic":5,"value":139,"top_keyword":"halloween horses","top_keyword_best_position":1,"keywords":2},
 {"url":"https://cavallo-inc.com/barefoot-barrel-racing/","sum_traffic":5,"value":110,"top_keyword":"barrel racing boots","top_keyword_best_position":7,"keywords":3},
 {"url":"https://cavallo-inc.com/using-cavallo-boots-for-hoof-rehab/","sum_traffic":5,"value":278,"top_keyword":"therapeutic hoof boots","top_keyword_best_position":7,"keywords":2},
 {"url":"https://cavallo-inc.com/cavallo-is-all-about-the-horse/","sum_traffic":5,"value":0,"top_keyword":"cavallo in english","top_keyword_best_position":8,"keywords":6},
 {"url":"https://cavallo-inc.com/category/the-barefoot-horse/","sum_traffic":4,"value":None,"top_keyword":"barefoot horse","top_keyword_best_position":7,"keywords":2},
 {"url":"https://cavallo-inc.com/product-category/hoof-boot/bfb-hoof-boots/","sum_traffic":4,"value":182,"top_keyword":"draft horse boots","top_keyword_best_position":5,"keywords":2},
 {"url":"https://cavallo-inc.com/megan-hensley-the-donkey-farrier-joins-cavallo/","sum_traffic":3,"value":None,"top_keyword":"donkey farrier","top_keyword_best_position":7,"keywords":1},
 {"url":"https://cavallo-inc.com/meet-the-leb-long-ear-donkey-hoof-boot/","sum_traffic":3,"value":None,"top_keyword":"donkey boots","top_keyword_best_position":7,"keywords":1},
 {"url":"https://cavallo-inc.com/we-are-all-flesh/","sum_traffic":3,"value":None,"top_keyword":"adelaide art gallery horse","top_keyword_best_position":1,"keywords":2},
 {"url":"https://cavallo-inc.com/product/mustad-hoof-shield/","sum_traffic":3,"value":315,"top_keyword":"hoof shield","top_keyword_best_position":5,"keywords":1},
 {"url":"https://cavallo-inc.com/reviews/","sum_traffic":3,"value":195,"top_keyword":"cavallo horse boots","top_keyword_best_position":2,"keywords":4},
 {"url":"https://cavallo-inc.com/product-category/hoof-boot-accessories/cavallo-hoof-boots-velcro-replacement-straps/","sum_traffic":3,"value":122,"top_keyword":"velcro boot straps","top_keyword_best_position":7,"keywords":1},
 {"url":"https://cavallo-inc.com/category/miniature-horses-vse/","sum_traffic":3,"value":152,"top_keyword":"mini horse boots","top_keyword_best_position":9,"keywords":1},
 {"url":"https://cavallo-inc.com/exchange-return-policy-page/","sum_traffic":3,"value":494,"top_keyword":"cavello","top_keyword_best_position":2,"keywords":1},
 {"url":"https://cavallo-inc.com/riding-in-wild-horse-country/","sum_traffic":3,"value":None,"top_keyword":"can you ride a wild horse","top_keyword_best_position":7,"keywords":2},
 {"url":"https://cavallo-inc.com/things-to-know/","sum_traffic":3,"value":195,"top_keyword":"cavallo horse boots","top_keyword_best_position":2,"keywords":6},
 {"url":"https://cavallo-inc.com/product/simple-hoof-boot-black/","sum_traffic":3,"value":203,"top_keyword":"simple boot","top_keyword_best_position":6,"keywords":1},
 {"url":"https://cavallo-inc.com/contact-us/","sum_traffic":3,"value":494,"top_keyword":"cavello","top_keyword_best_position":2,"keywords":3},
 {"url":"https://cavallo-inc.com/faq/cavallo-pastern-wraps/","sum_traffic":2,"value":38,"top_keyword":"cavallo pastern wraps","top_keyword_best_position":4,"keywords":2},
 {"url":"https://cavallo-inc.com/category/stories/saddle-pad-testimonials/","sum_traffic":2,"value":82,"top_keyword":"cavallo saddle pads","top_keyword_best_position":7,"keywords":2},
 {"url":"https://cavallo-inc.com/clb-boot-and-your-mini-horse/","sum_traffic":2,"value":221,"top_keyword":"clb boots","top_keyword_best_position":6,"keywords":1},
 {"url":"https://cavallo-inc.com/do-you-know-your-horses-weight/","sum_traffic":2,"value":3,"top_keyword":"chubby horses","top_keyword_best_position":1,"keywords":2},
 {"url":"https://cavallo-inc.com/product/simple-boot-replacement-straps/","sum_traffic":2,"value":53,"top_keyword":"replacement velcro straps for walking boot","top_keyword_best_position":9,"keywords":1},
 {"url":"https://cavallo-inc.com/wp-content/uploads/2024/10/CAVALLOBarefootTrim_002.pdf","sum_traffic":2,"value":56,"top_keyword":"barefoot trim","top_keyword_best_position":10,"keywords":1},
 {"url":"https://cavallo-inc.com/product/mustad-double-s-loop-hoof-knife/","sum_traffic":2,"value":None,"top_keyword":"loop knife","top_keyword_best_position":9,"keywords":1},
 {"url":"https://cavallo-inc.com/product-category/hoof-boot-accessories/hoof-boot-studs/","sum_traffic":2,"value":69,"top_keyword":"studded horse shoes","top_keyword_best_position":5,"keywords":1},
 {"url":"https://cavallo-inc.com/boots-that-stay-on-in-thick-snow-and-freezing-mud/","sum_traffic":2,"value":63,"top_keyword":"mud boots for horses","top_keyword_best_position":9,"keywords":2},
 {"url":"https://cavallo-inc.com/cavallo-boots-for-navicular/","sum_traffic":1,"value":None,"top_keyword":"navicular hoof","top_keyword_best_position":7,"keywords":1},
 {"url":"https://cavallo-inc.com/product/proflex/","sum_traffic":1,"value":24,"top_keyword":"splint boots","top_keyword_best_position":13,"keywords":1},
 {"url":"https://cavallo-inc.com/hoof-abscesses-bravely-facing-the-battle/","sum_traffic":1,"value":27,"top_keyword":"hoof boot for abscess","top_keyword_best_position":9,"keywords":1},
 {"url":"https://cavallo-inc.com/product/clb-cute-little-boots/","sum_traffic":1,"value":49,"top_keyword":"mini horse boots","top_keyword_best_position":7,"keywords":2},
 {"url":"https://cavallo-inc.com/cavallo-gives/","sum_traffic":1,"value":47,"top_keyword":"free horse stuff","top_keyword_best_position":9,"keywords":1},
 {"url":"https://cavallo-inc.com/hoof-care-for-the-winter-months/","sum_traffic":1,"value":None,"top_keyword":"horse hoof without hoof","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/mules-rocking-cavallo-boots/","sum_traffic":1,"value":28,"top_keyword":"mule boot","top_keyword_best_position":13,"keywords":2},
 {"url":"https://cavallo-inc.com/miraculous-simplicity-hoof/","sum_traffic":1,"value":None,"top_keyword":"horse hoof without nail","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/nailing-metal-to-your-horses-feet-hoof-hints/","sum_traffic":1,"value":None,"top_keyword":"horse feet metal","top_keyword_best_position":10,"keywords":1},
 {"url":"https://cavallo-inc.com/journey-with-wildebeests-contrasting-equiss-to-antelope-deep-in-the-heart-of-africa/","sum_traffic":1,"value":None,"top_keyword":"wildebeest hooves","top_keyword_best_position":8,"keywords":1},
 {"url":"https://cavallo-inc.com/faq/cavallo-hoof-boots-for-shod-horses/","sum_traffic":1,"value":0,"top_keyword":"shod horse hoof","top_keyword_best_position":11,"keywords":2},
 {"url":"https://cavallo-inc.com/are-you-treating-your-horse-with-bubble-wrap/","sum_traffic":1,"value":None,"top_keyword":"bubble horse","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/why-are-cavallo-hoof-boots-the-best/","sum_traffic":1,"value":6,"top_keyword":"what are hoof boots used for","top_keyword_best_position":5,"keywords":5},
 {"url":"https://cavallo-inc.com/where-the-rubber-meets-the-road-alternatives-to-metal-horseshoes/","sum_traffic":1,"value":None,"top_keyword":"rubber horse shoes","top_keyword_best_position":11,"keywords":1},
 {"url":"https://cavallo-inc.com/product-category/saddle-pads/english-saddle-pads/","sum_traffic":1,"value":23,"top_keyword":"english saddle pads","top_keyword_best_position":26,"keywords":1},
 {"url":"https://cavallo-inc.com/tom-seay-best-of-america-by-horseback-loves-cavallo/","sum_traffic":1,"value":None,"top_keyword":"tom seay","top_keyword_best_position":2,"keywords":2},
 {"url":"https://cavallo-inc.com/product/wedge-saddle-pad/","sum_traffic":1,"value":81,"top_keyword":"wedge pads for horses","top_keyword_best_position":11,"keywords":1},
 {"url":"https://cavallo-inc.com/product/trek-black-hoof-boot/","sum_traffic":1,"value":80,"top_keyword":"cavallo trek slim","top_keyword_best_position":3,"keywords":2},
 {"url":"https://cavallo-inc.com/contracted-heels-101/","sum_traffic":1,"value":None,"top_keyword":"contracted heels in horses","top_keyword_best_position":10,"keywords":1},
 {"url":"https://cavallo-inc.com/product-category/hoof-boot-accessories/hoof-boot-pads/protection-pads/","sum_traffic":1,"value":93,"top_keyword":"hoof protector","top_keyword_best_position":11,"keywords":1},
 {"url":"https://cavallo-inc.com/guy-mclean-an-excellent-judge-of-horse-equipment/","sum_traffic":1,"value":None,"top_keyword":"horse guy","top_keyword_best_position":1,"keywords":2},
 {"url":"https://cavallo-inc.com/product-category/saddle-pads/western-saddle-pads/","sum_traffic":0,"value":12,"top_keyword":"built up western saddle pad","top_keyword_best_position":13,"keywords":1},
 {"url":"https://cavallo-inc.com/why-trek-makes-the-perfect-therapy-rehab-hoof-boot/","sum_traffic":0,"value":0,"top_keyword":"best hoof boots for turnout","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/faq/cavallo-hoof-boots-for-turnout/","sum_traffic":0,"value":0,"top_keyword":"cavallo horse boots","top_keyword_best_position":9,"keywords":2},
 {"url":"https://cavallo-inc.com/product/raised-wither-saddle-pad/","sum_traffic":0,"value":14,"top_keyword":"cavallo saddle pad","top_keyword_best_position":12,"keywords":3},
 {"url":"https://cavallo-inc.com/we-winterize-our-houses-vehicles-why-not-winterize-your-horse/","sum_traffic":0,"value":11,"top_keyword":"steel horse snow boots","top_keyword_best_position":9,"keywords":1},
 {"url":"https://cavallo-inc.com/tag/poultice-boots/","sum_traffic":0,"value":5,"top_keyword":"horse poultice boots","top_keyword_best_position":10,"keywords":1},
 {"url":"https://cavallo-inc.com/about/","sum_traffic":0,"value":0,"top_keyword":"cavallo","top_keyword_best_position":42,"keywords":1},
 {"url":"https://cavallo-inc.com/product/hoof-boot-studs/","sum_traffic":0,"value":0,"top_keyword":"studded horse shoes","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/product/mustad-hoof-knives-right/","sum_traffic":0,"value":7,"top_keyword":"hoof knife for horses","top_keyword_best_position":12,"keywords":1},
 {"url":"https://cavallo-inc.com/product/leb-long-ear-boot-hoof-boot-for-donkeys-turquoise/","sum_traffic":0,"value":6,"top_keyword":"donkey hoof shoes","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/product/knife/","sum_traffic":0,"value":12,"top_keyword":"multi purpose knife","top_keyword_best_position":7,"keywords":2},
 {"url":"https://cavallo-inc.com/product/bfb-pastern-wraps/","sum_traffic":0,"value":0,"top_keyword":"pastern wraps for horses","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/product/heller-gr8at-red-tang-14-rasp/","sum_traffic":0,"value":34,"top_keyword":"red tang","top_keyword_best_position":6,"keywords":1},
 {"url":"https://cavallo-inc.com/what-is-white-line-disease/","sum_traffic":0,"value":None,"top_keyword":"white line disease apple cider vinegar","top_keyword_best_position":11,"keywords":1},
 {"url":"https://cavallo-inc.com/videos/","sum_traffic":0,"value":0,"top_keyword":"hoof boots","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/our-hoof-boot-technology/","sum_traffic":0,"value":0,"top_keyword":"hoof boots","top_keyword_best_position":45,"keywords":1},
 {"url":"https://cavallo-inc.com/product/full-monty-western-saddle-pad/","sum_traffic":0,"value":4,"top_keyword":"cavallo saddle pads","top_keyword_best_position":10,"keywords":1},
 {"url":"https://cavallo-inc.com/product/all-purpose-english-saddle-pad-performance-enhanced/","sum_traffic":0,"value":None,"top_keyword":"english pad","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/faq/cavallo-hoof-boots-durability-and-lifespan/","sum_traffic":0,"value":0,"top_keyword":"cavallo كريم","top_keyword_best_position":5,"keywords":3},
 {"url":"https://cavallo-inc.com/product/cavallo-proflex-splint-boots-redblack/","sum_traffic":0,"value":0,"top_keyword":"splint boot for horses","top_keyword_best_position":8,"keywords":2},
 {"url":"https://cavallo-inc.com/happy-riding-in-cavallos/","sum_traffic":0,"value":None,"top_keyword":"cavallos","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/natural-remedies-for-your-horse/","sum_traffic":0,"value":0,"top_keyword":"tea tree oil for horses","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/hoof-function-and-horse-shoes/","sum_traffic":0,"value":None,"top_keyword":"kuvalo shoes","top_keyword_best_position":10,"keywords":1},
 {"url":"https://cavallo-inc.com/product/break-away-halter/","sum_traffic":0,"value":10,"top_keyword":"red halter horse","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/product/hoof-pick/","sum_traffic":0,"value":0,"top_keyword":"hoof pick","top_keyword_best_position":48,"keywords":1},
 {"url":"https://cavallo-inc.com/emma-massingales-talented-herd-loves-their-cavallos/","sum_traffic":0,"value":None,"top_keyword":"cavallo emma","top_keyword_best_position":6,"keywords":1},
 {"url":"https://cavallo-inc.com/faq/sizing-and-measuring-cavallo-hoof-boots/","sum_traffic":0,"value":0,"top_keyword":"cavallo boot size chart","top_keyword_best_position":5,"keywords":1},
 {"url":"https://cavallo-inc.com/a-winter-laminitis-saga/","sum_traffic":0,"value":None,"top_keyword":"winterlaminitis","top_keyword_best_position":11,"keywords":1},
 {"url":"https://cavallo-inc.com/cavallo-hoof-boots-help-your-horse-on-gravel/","sum_traffic":0,"value":None,"top_keyword":"horse toe","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/product/cavallo-canine-leather-collar-kelly-green/","sum_traffic":0,"value":None,"top_keyword":"kelly cavallo","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/horse-psychology/","sum_traffic":0,"value":None,"top_keyword":"horse psychology","top_keyword_best_position":11,"keywords":1},
 {"url":"https://cavallo-inc.com/product/cavallo-canine-leather-leash-kelly-green/","sum_traffic":0,"value":None,"top_keyword":"kelly cavallo","top_keyword_best_position":1,"keywords":1},
 {"url":"https://cavallo-inc.com/faq/how-do-cavallo-hoof-boots-compare/","sum_traffic":0,"value":0,"top_keyword":"cavallo riding boots","top_keyword_best_position":14,"keywords":1},
 {"url":"https://cavallo-inc.com/cavallo-the-top-choice-for-boots-over-metal-shoes/","sum_traffic":0,"value":47,"top_keyword":"cavallo shoes","top_keyword_best_position":13,"keywords":2},
 {"url":"https://cavallo-inc.com/product/trekbuckle/","sum_traffic":0,"value":21,"top_keyword":"cavallo trek","top_keyword_best_position":6,"keywords":1},
 {"url":"https://cavallo-inc.com/whats-all-this-talk-about-white-line-disease/","sum_traffic":0,"value":None,"top_keyword":"white line disease apple cider vinegar","top_keyword_best_position":3,"keywords":1},
 {"url":"https://cavallo-inc.com/you-and-your-horse-a-sensory-relationship-touch/","sum_traffic":0,"value":0,"top_keyword":"how to learn about horses","top_keyword_best_position":1,"keywords":1},
]

def path_key(url):
    p = url.split("cavallo-inc.com", 1)[-1]
    if not p.startswith("/"):
        p = "/" + p
    return p.rstrip("/")  # normalize: no trailing slash

overlay = {}
for r in PAGES:
    overlay[path_key(r["url"])] = {
        "traffic": r["sum_traffic"],
        "value_usd": round((r["value"] or 0) / 100, 2),
        "top_keyword": r["top_keyword"],
        "position": r["top_keyword_best_position"],
        "ranking_keywords": r["keywords"],
    }

json.dump(overlay, open(os.path.join(BASE, "ahrefs_overlay.json"), "w"), indent=0)
print(f"Wrote {len(overlay)} ranked-page overlay entries to ahrefs_overlay.json")
